import { TrackerEntry, PlatformSession, CVSession, User, MockInterviewSession } from './types';

export const mockUsers: User[] = [
  { id: 'u1', name: 'Siddhartha Priya', email: 'siddhartha@lawsikho.in', role: 'MENTOR' },
  { id: 'u2', name: 'Veena Chandra', email: 'veena@lawsikho.in', role: 'MENTOR' },
  { id: 'u3', name: 'Akhya Tiwari', email: 'akhya@lawsikho.in', role: 'MENTOR' },
  { id: 'u4', name: 'Vartika Kulshrestha', email: 'vartika@lawsikho.in', role: 'MENTOR' },
  { id: 'u5', name: 'Tiya', email: 'tiya@lawsikho.in', role: 'CALLER' },
  { id: 'u6', name: 'Shipra J', email: 'shipra.j@addictivelearn.com', role: 'CALLER' },
  { id: 'u7', name: 'Jasmine K', email: 'jasmine.k@lawsikho.in', role: 'CALLER' },
  { id: 'u8', name: 'Shivangi G', email: 'shivangi.g@addictivelearn.com', role: 'CALLER' },
];

export const mockData: TrackerEntry[] = [
  {
    id: '1',
    timestamp: '20/06/2025 10:22:51',
    name: 'Neha Jakhar',
    email: 'nehajakhar12@gmail.com',
    phone: '8168745527',
    courseName: 'Diploma in Advanced C',
    enrollmentDate: '28/5/2025',
    profileLink: 'https://www.linkedin.com/in/neha',
    assistanceNeeded: 'I need assistance with my profile',
    isAvailableForSession: true,
    linkedinSupport: true,
    upworkSupport: false,
    fiverrSupport: true,
    cvImprovement: true,
    resumeWriting: true,
    mockInterview: false,
    schedulingCallTat: '27/06/2025',
  },
  {
    id: '2',
    timestamp: '20/06/2025 13:30:36',
    name: 'Prachi Singh',
    email: 'prachi.singh9451@gmail.com',
    phone: '6392858745',
    courseName: 'Advance contract drafting',
    enrollmentDate: '24/12/2024',
    profileLink: 'https://www.linkedin.com/in/prachi',
    assistanceNeeded: 'I would like guidance on Upwork',
    isAvailableForSession: true,
    linkedinSupport: true,
    upworkSupport: false,
    fiverrSupport: true,
    cvImprovement: true,
    resumeWriting: false,
    mockInterview: false,
    schedulingCallTat: '27/06/2025',
  },
  {
    id: '3',
    timestamp: '20/06/2025 17:07:20',
    name: 'Richa Joshi',
    email: 'richa91joshi@gmail.com',
    phone: '9643618625',
    courseName: 'International Business Law',
    enrollmentDate: '18/5/2025',
    profileLink: 'https://www.linkedin.com/in/richa',
    assistanceNeeded: 'CV Improvement and mock interview',
    isAvailableForSession: true,
    linkedinSupport: true,
    upworkSupport: false,
    fiverrSupport: false,
    cvImprovement: true,
    resumeWriting: true,
    mockInterview: false,
    schedulingCallTat: '27/06/2025',
  },
  {
    id: '4',
    timestamp: '20/06/2025 18:04:56',
    name: 'RICHA THAPA',
    email: 'richathapa18@gmail.com',
    phone: '8527786792',
    courseName: 'DIPLOMA IN CORPORATE',
    enrollmentDate: '10/6/2025',
    profileLink: 'https://www.linkedin.com/in/richathapa',
    assistanceNeeded: 'I need suggestions for Upwork',
    isAvailableForSession: true,
    linkedinSupport: true,
    upworkSupport: true,
    fiverrSupport: false,
    cvImprovement: false,
    resumeWriting: true,
    mockInterview: false,
    schedulingCallTat: '27/06/2025',
  },
  {
    id: '5',
    timestamp: '21/06/2025 01:44:55',
    name: 'JULIE MEHTA',
    email: 'SHAHJULIE2@GMAIL.COM',
    phone: '9594948828',
    courseName: 'Diploma in Advanced C',
    enrollmentDate: '2/5/2025',
    profileLink: 'https://www.linkedin.com/in/julie',
    assistanceNeeded: 'I have a resume',
    isAvailableForSession: true,
    linkedinSupport: true,
    upworkSupport: false,
    fiverrSupport: false,
    cvImprovement: true,
    resumeWriting: true,
    mockInterview: false,
    schedulingCallTat: '28/06/2025',
  },
  {
    id: '6',
    timestamp: '21/06/2025 10:55:36',
    name: 'Charmi Jogani',
    email: 'charmishah0507@gmail.com',
    phone: '9819308684',
    courseName: 'Diploma in Technology',
    enrollmentDate: '14/2/2025',
    profileLink: 'https://www.upwork.com/fr',
    assistanceNeeded: 'Lack of understanding',
    isAvailableForSession: true,
    linkedinSupport: false,
    upworkSupport: true,
    fiverrSupport: false,
    cvImprovement: false,
    resumeWriting: false,
    mockInterview: false,
    schedulingCallTat: '28/06/2025',
  }
];

export const mockSessions: PlatformSession[] = [
  {
    id: 's1',
    studentId: '4',
    name: 'RICHA THAPA',
    email: 'richathapa18@gmail.com',
    phone: '8527786792',
    source: 'Student Portal (Form)',
    brand: 'SkillArbitrage',
    platformType: 'LinkedIn',
    scheduledBy: 'tiya@lawsikho.in',
    scheduledTimestamp: '26/06/2025 15:46:36',
    scheduledDate: '30/06/2025',
    scheduledTime: '11:15',
    mentorAllocated: 'Mrinalini Deb',
    isGoogleMeetScheduled: true,
    googleMeetUrl: 'https://meet.google.com/kjs-vsef-vpn',
    isCancelled: false,
    cancellationReason: '',
  },
  {
    id: 's2',
    studentId: '4',
    name: 'RICHA THAPA',
    email: 'richathapa18@gmail.com',
    phone: '8527786792',
    source: 'Student Portal (Form)',
    brand: 'SkillArbitrage',
    platformType: 'Upwork',
    scheduledBy: 'tiya@lawsikho.in',
    scheduledTimestamp: '27/06/2025 14:34:37',
    scheduledDate: '27/06/2025',
    scheduledTime: '15:30',
    mentorAllocated: 'Anjali Singh',
    isGoogleMeetScheduled: false,
    googleMeetUrl: '',
    isCancelled: false,
    cancellationReason: '',
  },
  {
    id: 's3',
    studentId: '5',
    name: 'JULIE MEHTA',
    email: 'SHAHJULIE2@GMAIL.COM',
    phone: '9594948828',
    source: 'Student Portal (Form)',
    brand: 'SkillArbitrage',
    platformType: 'LinkedIn',
    scheduledBy: 'tiya@lawsikho.in',
    scheduledTimestamp: '26/06/2025 15:46:36',
    scheduledDate: '30/06/2025',
    scheduledTime: '11:15',
    mentorAllocated: 'Mrinalini Deb',
    isGoogleMeetScheduled: true,
    googleMeetUrl: 'https://meet.google.com/kjs-vsef-vpn',
    isCancelled: true,
    cancellationReason: 'The student herself mailed that she is occupied for some reason and will be unavailable for the slotted session and has asked for rescheduling.',
  },
  {
    id: 's4',
    studentId: '1',
    name: 'Neha Jakhar',
    email: 'nehajakhar12@gmail.com',
    phone: '8168745527',
    source: 'Agent Scheduler Form',
    brand: 'SkillArbitrage',
    platformType: 'LinkedIn',
    scheduledBy: 'bhawna.n@addictivelearn.com',
    scheduledTimestamp: '26/12/2025 12:32:29',
    scheduledDate: '26/12/2025',
    scheduledTime: '16:00',
    mentorAllocated: 'Bhawna Nihalani',
    isGoogleMeetScheduled: false,
    googleMeetUrl: '',
    isCancelled: false,
    cancellationReason: '',
  },
  {
    id: 's5',
    studentId: '10',
    name: 'Harish Venugopal',
    email: 'hvenugopal@yahoo.com',
    phone: '9035845843',
    source: 'Agent Scheduler Form',
    brand: 'SkillArbitrage',
    platformType: 'LinkedIn',
    scheduledBy: 'bhawna.n@addictivelearn.com',
    scheduledTimestamp: '07/02/2026 01:45:56',
    scheduledDate: '07/02/2025',
    scheduledTime: '12:00',
    mentorAllocated: 'Bhawna Nihalani',
    isGoogleMeetScheduled: true,
    googleMeetUrl: 'https://meet.google.com/abc-defg-hij',
    isCancelled: false,
    cancellationReason: '',
  },
  {
    id: 's6',
    studentId: '11',
    name: 'dinesh kumar',
    email: 'dinmca@gmail.com',
    phone: '9986157137',
    source: 'Student Portal (Form)',
    brand: 'SkillArbitrage',
    platformType: 'Upwork',
    scheduledBy: 'tiya@lawsikho.in',
    scheduledTimestamp: '26/06/2025 15:38:36',
    scheduledDate: '26/06/2025',
    scheduledTime: '17:00',
    mentorAllocated: 'Indrani Dutta',
    isGoogleMeetScheduled: false,
    googleMeetUrl: '',
    isCancelled: false,
    cancellationReason: '',
  },
  {
    id: 's7',
    studentId: '17',
    name: 'Aparajita Das',
    email: 'aparajitadas11@gmail.com',
    phone: '9873198573',
    source: 'Student Portal (Form)',
    brand: 'SkillArbitrage',
    platformType: 'Fiverr',
    scheduledBy: 'tiya@lawsikho.in',
    scheduledTimestamp: '26/06/2025 17:24:37',
    scheduledDate: '30/06/2025',
    scheduledTime: '12:00',
    mentorAllocated: 'Vartika Kulshrestha',
    isGoogleMeetScheduled: true,
    googleMeetUrl: 'https://meet.google.com/bow-qium-mzn',
    isCancelled: false,
    cancellationReason: '',
  }
];

export const mockCVSessions: CVSession[] = [
  {
    id: 'cv1',
    studentId: 'cvs1',
    name: 'Tavishi Jain',
    email: 'jaintavishi1998@gmail.com',
    phone: '7744912831',
    source: 'Student Portal (Form)',
    brand: 'LawSikho',
    sessionType: 'CV Improvement',
    scheduledBy: 'tiya@lawsikho.in',
    scheduledTimestamp: '26/06/2025 16:55:55',
    scheduledDate: '27/06/2025',
    scheduledTime: '09:45',
    mentorAllocated: 'Siddhartha Priya',
    isGoogleMeetScheduled: false,
    googleMeetUrl: '',
    recordingLink: '',
    isCancelled: false,
    cancellationReason: '',
    aiStatus: '',
    aiReport: '',
  },
  {
    id: 'cv2',
    studentId: '5',
    name: 'JULIE MEHTA',
    email: 'SHAHJULIE2@GMAIL.COM',
    phone: '9594948828',
    source: 'Student Portal (Form)',
    brand: 'SkillArbitrage',
    sessionType: 'CV Improvement',
    scheduledBy: 'tiya@lawsikho.in',
    scheduledTimestamp: '26/06/2025 15:47:05',
    scheduledDate: '27/06/2025',
    scheduledTime: '12:00',
    mentorAllocated: 'Siddhartha Priya',
    isGoogleMeetScheduled: false,
    googleMeetUrl: '',
    recordingLink: '',
    isCancelled: false,
    cancellationReason: '',
    aiStatus: '',
    aiReport: '',
  },
  {
    id: 'cv3',
    studentId: 'cvs3',
    name: 'Sanjana Prajapati',
    email: 'sanjanaprajapati.law@gmail.com',
    phone: '7066553421',
    source: 'Student Portal (Form)',
    brand: 'LawSikho',
    sessionType: 'CV Improvement',
    scheduledBy: 'shipra.j@addictivelearn.com',
    scheduledTimestamp: '27/06/2025 15:41:58',
    scheduledDate: '28/06/2025',
    scheduledTime: '09:45',
    mentorAllocated: 'Siddhartha Priya',
    isGoogleMeetScheduled: true,
    googleMeetUrl: 'https://meet.google.com/vzz-sjkc-zct',
    recordingLink: 'https://drive.google.com/file/d/1nk_vGdOpsNzNT7BqdPXEtEyMy6rM2XUx/view',
    isCancelled: false,
    cancellationReason: '',
    aiStatus: 'Completed',
    aiReport: 'https://docs.google.com/open?id=1jiWifKztCQ8I0xu2bplm6k2XASu4Aqy9_mXsYI0H0oU',
  },
  {
    id: 'cv4',
    studentId: '3',
    name: 'Richa Joshi',
    email: 'richa91joshi@gmail.com',
    phone: '9643618625',
    source: 'Student Portal (Form)',
    brand: 'LawSikho',
    sessionType: 'CV Improvement',
    scheduledBy: 'tiya@lawsikho.in',
    scheduledTimestamp: '27/06/2025 13:07:55',
    scheduledDate: '28/06/2025',
    scheduledTime: '12:45',
    mentorAllocated: 'Siddhartha Priya',
    isGoogleMeetScheduled: true,
    googleMeetUrl: 'https://meet.google.com/fvb-ihef-mrv',
    recordingLink: '',
    isCancelled: false,
    cancellationReason: '',
    aiStatus: 'Mentor Failed to Record',
    aiReport: 'Not Available',
  },
  {
    id: 'cv5',
    studentId: 'cvs5',
    name: 'Vishwa S. Thakkar',
    email: 'vishvathakkar9@gmail.com',
    phone: '6382031594',
    source: 'Student Portal (Form)',
    brand: 'SkillArbitrage',
    sessionType: 'CV Improvement',
    scheduledBy: 'tiya@lawsikho.in',
    scheduledTimestamp: '27/06/2025 14:55:56',
    scheduledDate: '30/06/2025',
    scheduledTime: '13:00',
    mentorAllocated: 'Veena Chandra',
    isGoogleMeetScheduled: true,
    googleMeetUrl: 'https://meet.google.com/ukw-tbpu-otk',
    recordingLink: 'https://drive.google.com/file/d/1s6SXrzad1KgevPWvQZ_PBEbouY-ZRDhd/view',
    isCancelled: false,
    cancellationReason: '',
    aiStatus: 'Completed',
    aiReport: 'https://docs.google.com/open?id=1qspi-_m5mvokBqhOSlrm0qm1li1aP9A0P2xjbqmvqA4',
  }
];

export const mockMockInterviewSessions: MockInterviewSession[] = [
  {
    id: 'mock1',
    studentId: 'm1',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@example.com',
    phone: '9876543210',
    source: 'Student Portal (Form)',
    brand: 'SkillArbitrage',
    sessionType: 'Mock Interview',
    scheduledBy: 'tiya@lawsikho.in',
    scheduledTimestamp: '28/06/2025 10:00:00',
    scheduledDate: '01/07/2025',
    scheduledTime: '11:00',
    mentorAllocated: 'Siddhartha Priya',
    isGoogleMeetScheduled: true,
    googleMeetUrl: 'https://meet.google.com/abc-defg-hij',
    recordingLink: 'https://drive.google.com/file/d/recording1',
    isCancelled: false,
    cancellationReason: '',
    aiStatus: 'Completed',
    aiReport: 'https://docs.google.com/open?id=report1',
  },
  {
    id: 'mock2',
    studentId: 'm2',
    name: 'Priya Verma',
    email: 'priya.verma@example.com',
    phone: '9876543211',
    source: 'Student Portal (Form)',
    brand: 'SkillArbitrage',
    sessionType: 'Mock Interview',
    scheduledBy: 'shipra.j@addictivelearn.com',
    scheduledTimestamp: '28/06/2025 11:30:00',
    scheduledDate: '01/07/2025',
    scheduledTime: '14:00',
    mentorAllocated: 'Veena Chandra',
    isGoogleMeetScheduled: true,
    googleMeetUrl: 'https://meet.google.com/xyz-pqrs-tuv',
    recordingLink: '',
    isCancelled: false,
    cancellationReason: '',
    aiStatus: 'Pending',
    aiReport: 'Not Available',
  }
];
